name: fasterqr
description: "Fater Qr"

publish_to: 'none'


version: 1.1.0+2

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter



 # State Management
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6

  # QR Code and Scanning
  mobile_scanner: ^5.1.1
  scan: ^1.6.0
  qr_flutter: ^4.1.0

  # Media and Animations
  lottie: any
  images_picker: ^1.2.11
  gallery_saver: ^2.3.2

  # UI and Widgets
  cupertino_icons: ^1.0.6
  toggle_switch: ^2.3.0
  fluttertoast: ^8.2.6
  font_awesome_flutter: ^10.7.0

  # Audio
  audioplayers: ^6.0.0

  # Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Sharing and URL
  flutter_share: ^2.0.0
  url_launcher: ^6.3.0

  # Permissions
  permission_handler: ^11.3.1

  # Path Provider
  path_provider: ^2.1.3
 
  

dev_dependencies:
  hive_generator: ^2.0.1
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^4.0.0


flutter:

 
  uses-material-design: true

  
  assets:
    - assets/logo/
    - assets/lottie_animation/
    - assets/imgs/
    - assets/sounds/

  fonts:
    - family: PTSerif
      fonts:
        - asset: fonts/PTSerif-Bold.ttf
        - asset: fonts/PTSerif-BoldItalic.ttf
        - asset: fonts/PTSerif-Italic.ttf
        - asset: fonts/PTSerif-Regular.ttf

